{% set python_min = '3.10' %}
{% set name = "msibi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/msibi/archive/refs/tags/{{ version }}.tar.gz
  sha256: 96305ae30d5e0ee70192c6fc16689ef0a5ba46a9286f0d43e3d7e3ced73d5b0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - freud >=3.4,<4.0
    - cmeutils >=1.4
    - gsd >=3.0,<=4.0
    - hoomd >=5.0
    - numpy >=2.0,<2.3
    - pandas >=2.3,<3.0
    - mdanalysis >=2.9,<3.0
    - more-itertools
    - pip
    - python >={{ python_min }},<=3.13
    - matplotlib-base

test:
  imports:
    - msibi 
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mosdef-hub/msibi
  summary: 'Python package for performing multi-state iterative Boltzmann inversion.'
  description: |
    An intuitive python API for developing coarse-grain potentials using the multi-state
    iterative Boltzmann inversion (MSIBI) method. 
    msibi is able to optimize bond-stretching, bond-bending, non-bonded pairs and bonded dihedral
    potentials where multiple optimizations can be ran in sequence to create a complete coarse 
    grain forcefield.
    msibi utilizes the HOOMD-Blue simulation engine, and can therefore run on compatible GPU-hardware.
    The table potentials created by msibi are useable with LAMMPS, GROMACS, HOOMD-Blue, or any
    simulation engine that supports tabulated potentials.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://msibi.readthedocs.io/en/latest/
  dev_url: https://github.com/mosdef-hub/msibi

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - CalCraven
